# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt inc_append_history

source $HOME/.dotfiles/roles/zsh/env.zsh
source $HOME/.dotfiles/roles/zsh/path.zsh
source $HOME/.dotfiles/roles/zsh/config.zsh

# Enable vim mode
bindkey -v
KEYTIMEOUT=1

source "$ZDOTDIR/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# zinit ice wait lucid atload"zicompinit; zicdreplay" blockf for \
#     zsh-users/zsh-completions

zinit for atload"zicompinit; zicdreplay" \
    blockf lucid wait zsh-users/zsh-completions

zinit light zsh-users/zsh-autosuggestions
zinit ice wait lucid; zinit light zdharma-continuum/fast-syntax-highlighting
zinit light trystan2k/zsh-tab-title
zinit ice wait lucid; zinit light sineto/web-search

zinit ice depth=1; zinit light romkatv/powerlevel10k

[ -f $HOME/.bash_aliases ] && source $HOME/.bash_aliases
[ -f $HOME/.r1_aliases ] && source $HOME/.r1_aliases

if [[ -s "${HOME}/.config/broot/launcher/bash/br" ]]; then
  source "${HOME}/.config/broot/launcher/bash/br"
fi

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Cycle through history based on characters already typed on the line
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Use rg to respect .gitignore
export FZF_DEFAULT_COMMAND='rg --hidden --ignore .git -g ""'

if (($+commands[rbenv])); then
  eval "$(rbenv init -)"
fi

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh

[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

fpath+=${ZDOTDIR:-~}/.zsh_functions

export N_PREFIX=$HOME/.local/n
PATH=$N_PREFIX/bin:$PATH

export PYENV_ROOT="$HOME/.pyenv"
# PATH="$PYENV_ROOT/bin:$PATH"
PATH="$PATH:$PYENV_ROOT/bin"

export PNPM_HOME="/Users/horus/.local/share/pnpm"
PATH="$PNPM_HOME:$PATH"

if (($+commands[pyenv])); then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

pyenv-brew-relink() {
    rm -f "$HOME/.pyenv/versions/*-brew"
    for i in $(brew --cellar)/python* ; do
        ln -s -f "$p" "$HOME/.pyenv/versions/${i##/*/}-brew"
    done
    pyenv rehash
}

if (($+commands[thefuck])); then
  eval $(thefuck --alias)
fi

if (($+commands[zoxide])); then
  eval "$(zoxide init zsh)"
fi

source $HOME/.dotfiles/roles/zsh/aliases.zsh

# To customize prompt, run `p10k configure` or edit ~/.dotfiles/roles/zsh/files/p10k.zsh.
[[ ! -f ~/.dotfiles/roles/zsh/files/p10k.zsh ]] || source ~/.dotfiles/roles/zsh/files/p10k.zsh

# p10k prompt custom colors =====================
  # typeset -g ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

  # OS identifier color.
  # typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
  # typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=13

  # Current time color.
  # typeset -g POWERLEVEL9K_TIME_FOREGROUND=232
  # typeset -g POWERLEVEL9K_TIME_BACKGROUND=4
  
  ##################################[ dir: current directory ]##################################
  # Current directory background color.
  # typeset -g POWERLEVEL9K_DIR_BACKGROUND=5
  # Default current directory foreground color.
  # typeset -g POWERLEVEL9K_DIR_FOREGROUND=236
  # If directory is too long, shorten some of its segments to the shortest possible unique
  # prefix. The shortened directory can be tab-completed to the original.
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  # Replace removed segment suffixes with this symbol.
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  # Color of the shortened directory segments.
  # typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=232
  # Color of the anchor directory segments. Anchor segments are never shortened. The first
  # segment is always an anchor.
  # typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=237
  # Display anchor directory segments in bold.
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true


