- name: Install latest nodejs lts with nvm
  shell: source "{{xdg_config_home}}/zsh/.zshrc" && nvm install {{node_version}}
  args:
    executable: /usr/bin/zsh

- name: Install nodejs tools
  shell: source "{{xdg_config_home}}/zsh/.zshrc" && npm i -g cloc grunt-cli npmlist nws diff-so-fancy
  args:
    executable: /usr/bin/zsh
