package_upgrade: yes
apt_packages:
  - build-essential
  - curl
  - htop
  - ripgrep
  - bat
  - micro
  - p7zip

  # rbenv-build deps
  - autoconf
  - bison
  - build-essential
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm6
  - libgdbm-dev

  # GUI
  # - chromium-browser

dnf_packages:
  - htop
  - ripgrep
  - micro
  - bat
  - p7zip

  # rbenv-build deps
  - automake
  - gdbm-devel
  - libffi-devel
  - libyaml-devel
  - libopenssl-devel
  - ncurses-devel
  - readline-devel
  - zlib-devel

  # GUI
  # - chromium-browser

remove_packages:
  - rhythmbox
  - thunderbird
