- name: Clone fzf repository to {{xdg_data_home}}/fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{xdg_data_home}}/fzf"

- name: Install fzf
  command: "{{xdg_data_home}}/fzf/install --all --xdg --no-fish"
