- apt_repository: Add git-core ppa
    repo: ppa:git-core/ppa
    update_cache: no

- apt_repository: Add chrome ppa
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome    

- name: Upgrade apt
  apt: upgrade=full
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    pkg: "{{ apt_packages }}"
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ apt_packages }}"

- name: Remove apt packages
  apt:
    pkg: "{{ remove_packages }}"
    state: absent
  become: yes
  become_user: root
  become_method: sudo
