- name: Add git-core ppa
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Add google chrome apt signing key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add chrome ppa
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Update apt package info
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Upgrade apt
  apt:
    upgrade: full
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    pkg: "{{ apt_packages }}"
  become: yes
  become_user: root
  become_method: sudo

- name: Install ripgrep .deb package from github
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
  become: yes
  become_user: root
  become_method: sudo

- name: Install bat .deb package from github
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.17.1/bat_0.17.1_amd64.deb
  become: yes
  become_user: root
  become_method: sudo
# - name: Remove unused packages
#   command: apt purge "{{ ubuntu_unused_packages }}"
#   become: yes
#   become_user: root
#   become_method: sudo

# - name: Remove unused fonts
#   command: apt purge "{{ ubuntu_unused_fonts }}"
#   become: yes
#   become_user: root
#   become_method: sudo
