- name: Add git-core ppa
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Add google chrome apt signing key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add chrome ppa
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Add sublime-text 3 apt signing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add sublime-text ppa
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: sublime-text
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Update apt package info
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Upgrade apt
  apt:
    upgrade: full
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    pkg: "{{ apt_packages }}"
  become: yes
  become_user: root
  become_method: sudo

- name: Install ripgrep .deb package from github
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep_12.0.1_amd64.deb
  become: yes
  become_user: root
  become_method: sudo

#- name: Download ripgrep deb package from github
#  get_url:
#    url: https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep_12.0.1_amd64.deb
#    dest: /tmp/ripgrep.deb

- name: Remove rhythmbox
  command: apt remove --purge '?name(rhythmbox)'
  become: yes
  become_user: root
  become_method: sudo

- name: Remove thunderbird
  command: apt remove --purge '?name(thunderbird)'
  become: yes
  become_user: root
  become_method: sudo

- name: Remove apt packages
  apt:
    pkg: "{{ remove_packages }}"
    state: absent
  become: yes
  become_user: root
  become_method: sudo
