- name: Enable Fedora Copr for neovim nightly
  community.general.copr:
    name: agriffis/neovim-nightly
  become: yes
  become_user: root
  become_method: sudo

- name: Install the latest version of Neovim and deps
  dnf:
    name:
      - neovim
      - python3-neovim
    state: latest
  become: yes
  become_user: root
  become_method: sudo
