# Installation
- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Plugin manager
- name: Make sure vim-plug directory exists
  file: path="{{xdg_data_home}}/nvim/site/autoload" state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{xdg_data_home}}/nvim/site/autoload/plug.vim"

# Snippets
- name: Makes sure UltiSnips directory exists
  file: path="{{xdg_config_home}}/nvim/UltiSnips" state=directory

- name: Symlink all snippet files
  file:
    src: "{{ dotfiles_home }}/roles/nvim/files/{{item}}"
    dest: "{{xdg_config_home}}/nvim/UltiSnips/{{item}}"
    state: link
  with_items:
    - "javascript.snippets"

# Configuration
- name: Check if nvim init exists
  stat: path="{{xdg_config_home}}/nvim/init.vim"
  register: nvim_init_stat
  failed_when: False

- name: Backup nvim init
  command: mv "{{xdg_config_home}}/nvim/init.vim" "{{xdg_config_home}}/nvim/init.vim.bak"
  args:
    creates: "{{xdg_config_home}}/nvim/init.vim.bak"
  when: nvim_init_stat.stat.exists

- name: Create nvim config directory
  file:
    path: "{{xdg_config_home}}/nvim"
    state: directory
    mode: "0755"

- name: Symlink nvim config
  file:
    src: "{{dotfiles_home}}/roles/nvim/files/init.vim"
    dest: "{{xdg_config_home}}/nvim/init.vim"
    state: link

- name: Link nvim config
  file:
    src: "{{dotfiles_home}}/roles/nvim/files/{{item}}"
    dest: "{{xdg_config_home}}/nvim/{{item}}"
    state: link
    force: yes
  with_items:
    - "paths.vim"
    - "general_settings.vim"
    - "plugins.vim"
    - "key_mappings.vim"

- name: Ensures themes dir exists
  file: path="{{xdg_config_home}}/nvim/themes" state=directory

- name: Link nvim onedark theme
  file:
    src: "{{dotfiles_home}}/roles/nvim/files/onedark.vim"
    dest: "{{xdg_config_home}}/nvim/themes/onedark.vim"
    state: link
    force: yes

# - name: Install plugins
#   command: nvim +PlugInstall +qall
#   when: install_plugins
