- name: Add neovim unstable ppa
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    update_cache: no
  become: yes
  become_user: root
  become_method: sudo

- name: Update apt package info
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install neovim prerequisites
  apt:
    pkg:
      - python3-dev
      - python3-pip
      - xclip
  become: yes
  become_user: root
  become_method: sudo

- name: Install pynvim
  command: python3 -m pip install --user --upgrade pynvim

- name: Install neovim with apt
  apt:
    name: neovim
  become: yes
  become_user: root
  become_method: sudo
