- name: Update apt package info
  apt:
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install neovim prerequisites
  apt:
    pkg:
      - python3-dev
      - python3-pip
      - xclip
  become: yes
  become_user: root
  become_method: sudo

- name: Install pynvim
  command: python3 -m pip install --user --upgrade pynvim

- name: Install neovim appImage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /opt/nvim.appimage
    mode: '0755'
  become: yes
  become_user: root
  become_method: sudo

- name: Create nvim link
  ansible.builtin.file:
    src: /opt/nvim.appimage
    dest: /usr/bin/nvim
    state: link
  become: yes
  become_user: root
  become_method: sudo
