- name: Install ruby {{version}}
  shell: source "{{xdg_config_home}}/zsh/.zshrc" && rbenv install ruby {{version}}
  args:
    executable: /usr/bin/zsh

- name: Set global version for ruby to {{version}}
  shell: source "{{xdg_config_home}}/zsh/.zshrc" && rbenv global {{version}}
  args:
    executable: /usr/bin/zsh

- name: Install ruby gems
  shell: source "{{xdg_config_home}}/zsh/.zshrc" && gem install compass
  args:
    executable: /usr/bin/zsh
